[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn run build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn run build:preview"

[[redirects]]
  from = "/services/"
  to = "/pricing/"

[[redirects]]
  from = "/de/angebot/"
  to = "/de/preise/"

[[redirects]]
  from = "/fr/offre/"
  to = "/fr/tarifs/"
  
[[redirects]]
  from = "/de/identitaetspruefung/"
  to = "/de/qes-freischalten/"

[[redirects]]
  from = "/de/qes-erklaert/"
  to = "/de/signaturstandards/"

[[redirects]]
  from = "/identify/"
  to = "/enable-qes/"

[[redirects]]
  from = "/qes-explained/"
  to = "/signaturestandards/"

[[redirects]]
  from = "/fr/identifions/"
  to = "/fr/debloquez-qes/"

[[redirects]]
  from = "/fr/qes-explique/"
  to = "/fr/normessignature/"

[[redirects]]
  from = "/prices/"
  to = "/pricing/"

[[redirects]]
  from = "/fr/debloquez-qes"
  to = "/fr/debloquez-seq/"

[[redirects]]
  from = "/fr/validateur-qes/"
  to = "/fr/validateur-seq/"

[[redirects]]
  from = "/careers/378/account-executive-ch/"
  to = "/careers/"

[[redirects]]
  from = "/careers/294/country-manager-de/"
  to = "/careers/"

[[redirects]]
  from = "/careers/172/customer-success-manager-de/"
  to = "/careers/"

[[redirects]]
  from = "/careers/465/sales-manager-de/"
  to = "/careers/"

[[redirects]]
  from = "/de/karriere/378/account-executive-ch/"
  to = "/de/karriere/"

[[redirects]]
  from = "/de/karriere/294/country-manager-de/"
  to = "/de/karriere/"

[[redirects]]
  from = "/de/karriere/172/customer-success-manager-de/"
  to = "/de/karriere/"

[[redirects]]
  from = "/de/karriere/465/sales-manager-de/"
  to = "/de/karriere/"

[[redirects]]
  from = "/fr/carriere/378/account-executive-ch/"
  to = "/fr/carriere/"

[[redirects]]
  from = "/fr/carriere/294/country-manager-de/"
  to = "/fr/carriere/"

[[redirects]]
  from = "/fr/carriere/172/customer-success-manager-de/"
  to = "/fr/carriere/"

[[redirects]]
  from = "/fr/carriere/465/sales-manager-de/"
  to = "/fr/carriere/"

[[redirects]]
  from = "/careers/268/sales-consultant/"
  to = "/careers/"

[[redirects]]
  from = "/de/karriere/268/sales-consultant/"
  to = "/de/karriere/"

[[redirects]]
  from = "/fr/carriere/268/sales-consultant/"
  to = "/fr/carriere/"

[[redirects]]
  from = "/fr/maximiser-force-probante/"
  to = "/fr/augmenter-force-probante/"











