[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn run build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn run build:preview"

redirects = [
  {from = "/de/identitaetspruefung", to = "/de/qes-freischalten"},
  {from = "/de/qes-erklaert/", to = "/de/signaturstandards/"},
  {from = "/identify/", to = "/enable-qes/"},
  {from = "/qes-explained/", to = "/signaturestandards/"},
  {from = "/fr/identifions/", to = "/fr/debloquez-qes/"},
  {from = "/fr/qes-explique/", to = "/fr/normessignature/"},
  ]
