[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn run build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn run build:preview"

[[redirects]]
  from = "/*/index.html"
  to = "/de/:splat/index.html"
  conditions = {Language = ["de","de-ch","de-de","de-at","de-li","de-lu"]}