baseurl: /
title: Skribble
languages:
  de:
    params:
      description: Rechtsgültig elektronisch signieren mit Skribble
    languageName: Deutsch
    weight: 2
    contentDir: content/german
    menu:
      main:
        - name: Über uns
          url: /ueber-uns/
          weight: 5
        - name: Team
          url: /team/
          weight: 10
        - name: Kontakt
          url: /kontakt/
          weight: 15
      footer:
        - name: Disclaimer
          url: /de/disclaimer
        - name: Impressum
          url: /de/impressum
  en:
    params:
      description: Sign...
    languageName: English
    weight: 1
    contentDir: content/english
    menu:
      main:
        - name: About
          url: /about/
          weight: 5
        - name: Team
          url: /team/
          weight: 10
        - name: Contact
          url: /contact/
          weight: 15
      footer:
        - name: Privacy Policy
          url: /privacy/
        - name: Imprint
          url: /imprint/
