baseurl: /
languages:
  de:
    params:
      description: Rechtsgültig elektronisch signieren mit Skribble
    languageName: Deutsch
    weight: 2
    contentDir: content/german
    menu:
      main:
        - name: Über uns
          url: /de/ueber-uns/
        - name: Kontakt
          url: /de/kontakt/
      footer:
        - name: Disclaimer
          url: /de/disclaimer
        - name: Impressum
          url: /de/impressum
  en:
    params:
      description: Sign...
    languageName: English
    weight: 1
    contentDir: content/english
    menu:
      main:
        - name: About
          url: /about/
        - name: Contact
          url: /contact/
      footer:
        - name: Privacy Policy
          url: /privacy/
        - name: Imprint
          url: /imprint/
