baseurl: /
title: Skribble
languages:
  de:
    languageName: Deutsch
    weight: 2
    contentDir: content/german
    menu:
      main:
        - name: Angebot
          url: /de/angebot/
          weight: 5
        - name: Identifikation
          url: /de/identifikation/
          weight: 15
        - name: Kontakt
          url: /de/kontakt/
          weight: 20
      footer1:
        - name: Angebot
          url: /de/angebot/
          weight: 5
        - name: Identifikation
          url: /de/identifikation/
          weight: 10
      footer2:
        - name: Mission
          url: /de/ueber-uns/
          weight: 5
        - name: Team
          url: /de/team/
          weight: 10
        - name: Medien
          url: /de/medien/
          weight: 15
      footer3:
        - name: Help-Center
          url: https://help.skribble.com/deutsch
          weight: 5
      footer4:
        - name: Datenschutzbestimmungen
          url: /de/datenschutz
          weight: 10
        - name: Impressum
          url: /de/impressum
          weight: 15
    header:
      login:
        label: Login
        href: https://my.skribble.com/login?lang=de
      tryItOut:
        label: Jetzt ausprobieren
        href: https://my.skribble.com/signup?lang=de
      makeAnAppointment:
        label: Jetzt Termin vereinbaren
        href: https://help.skribble.com/meetings/simon79/beratung-zu-identifikationslsungen
    footer:
      navigation:
        titleColumn1: Plattform
        titleColumn2: Über uns
        titleColumn3: Ressourcen
      newsletterTitle: Newsletter
      newsletterText: Elektronische Signaturen und digitales Vertrauen sind brandaktuelle Themen. Bleibe auf dem Laufenden! <br class="hide-for-mobile">Siehe unsere <a href="/de/datenschutz">Datenschutzerklärungen</a>.
  en:
    languageName: English
    weight: 1
    contentDir: content/english
    menu:
      main:
        - name: Services
          url: /services/
          weight: 10
        - name: Identification
          url: /identification/
          weight: 15
        - name: Contact
          url: /contact/
          weight: 20
      footer1:
        - name: Services
          url: /services/
          weight: 5
        - name: Identification
          url: /identification/
          weight: 10
      footer2:
        - name: Mission
          url: /about/
          weight: 5
        - name: Team
          url: /team/
          weight: 10
        - name: Press room
          url: /pressroom/
          weight: 15
      footer3:
        - name: Help-Center
          url: https://help.skribble.com/english
          weight: 5
      footer4:
        - name: Privacy Policy
          url: /privacy/
          weight: 10
        - name: Imprint
          url: /imprint/
          weight: 15
    header:
      login:
        label: Login
        href: https://my.skribble.com/login
      tryItOut:
        label: Try it out
        href: https://my.skribble.com/signup
      makeAnAppointment:
        label: Make an appointment
        href: https://help.skribble.com/meetings/simon79/learn-about-skribbles-identification-means
    footer:
      navigation:
        titleColumn1: Platform
        titleColumn2: About us
        titleColumn3: Resources
      newsletterTitle: Newsletter
      newsletterText: Electronic signatures and digital trust are hot topics. <br class="hide-for-mobile">Stay up to date! See our <a href="/privacy">privacy policy</a>.
  fr:
    languageName: Français
    weight: 3
    contentDir: content/french
    menu:
      main:
        - name: Offre
          url: /fr/offre/
          weight: 5
        - name: Identification
          url: /fr/identification/
          weight: 15
        - name: Contact
          url: /fr/contact/
          weight: 20
      footer1:
        - name: Offre
          url: /fr/offre/
          weight: 5
        - name: Identification
          url: /fr/identification/
          weight: 15
      footer2:
        - name: Mission
          url: /fr/mission/
          weight: 5
        - name: Equipe
          url: /fr/equipe/
          weight: 10
        - name: Médias
          url: /fr/medias/
          weight: 20
      footer3:
        - name: Centre d'assistance
          url: https://help.skribble.com/francais
          weight: 5
      footer4:
        - name: Politique de Confidentialité
          url: /fr/politique-de-confidentialite
          weight: 10
        - name: Impressum
          url: /fr/impressum
          weight: 15
    header:
      login:
        label: Login
        href: https://my.skribble.com/login?lang=fr
      tryItOut:
        label: Essayer maintenant
        href: https://my.skribble.com/signup?lang=fr
      makeAnAppointment:
        label: Fixer un rendez-vous
        href: https://help.skribble.com/meetings/simon79/conseil
    footer:
      navigation:
        titleColumn1: Plateforme
        titleColumn2: À propos de nous
        titleColumn3: Ressources
      newsletterTitle: Newsletter
      newsletterText: Les signatures électroniques et la confiance numérique sont des sujets d'actualité. Restez au courant ! <br class="hide-for-mobile">Consultez notre <a href="/fr/politique-de-confidentialite/" target="_blank">politique de confidentialité</a>.
