baseurl: /
title: Skribble
languages:
  de:
    languageName: Deutsch
    weight: 2
    contentDir: content/german
    menu:
      main:
        - name: Über uns
          url: /ueber-uns/
          weight: 5
        - name: Identifikation
          url: /identifikation/
          weight: 15
        - name: Kontakt
          url: /kontakt/
          weight: 20
      footer1:
        - name: Identifikation
          url: /identifikation/
          weight: 15
      footer2:
        - name: Über uns
          url: /ueber-uns/
          weight: 5
        - name: Team
          url: /team/
          weight: 10
        - name: Kontakt
          url: /kontakt/
          weight: 20
      footer4:
        - name: Datenschutzbestimmungen
          url: /de/datenschutz
          weight: 10
        - name: Impressum
          url: /de/impressum
          weight: 15
    header:
      login:
        label: Login
        href: https://my.skribble.com/login?lang=de
      tryItOut:
        label: Jetzt ausprobieren
        href: https://my.skribble.com/signup?lang=de
    footer:
      navigation:
        titleColumn1: Plattform
        titleColumn2: Über uns
      newsletterTitle: Newsletter
      newsletterText: Elektronische Signaturen und digitales Vertrauen sind brandaktuelle Themen. Bleibe auf dem Laufenden! Siehe unsere <a href="/datenschutz">Datenschutzerklärugen</a>.
  en:
    languageName: English
    weight: 1
    contentDir: content/english
    error:
      title: Gone with the wind
      subtitle: "This page doesn't exist or has moved.<br>We apologize for the inconvenience."
      image:
        alt:
        filename: "error-404"
        natural_width: 407
      text: "You can return to home, or try looking on our <a href=\"https://help.skribble.com/english\">Help Center</a> if you need a hand. Perhaps you like 404 page. If so, you are welcome to stay for as long as you like :)"
      button:
        label: Return to homepage
        href:
    menu:
      main:
        - name: About
          url: /about/
          weight: 5
        - name: Identification
          url: /identification/
          weight: 15
        - name: Contact
          url: /contact/
          weight: 20
      footer1:
        - name: Identification
          url: /identification/
          weight: 15
      footer2:
        - name: About
          url: /about/
          weight: 5
        - name: Team
          url: /team/
          weight: 10
        - name: Contact
          url: /contact/
          weight: 20
      footer4:
        - name: Privacy Policy
          url: /privacy/
          weight: 10
        - name: Imprint
          url: /imprint/
          weight: 15
    header:
      login:
        label: Login
        href: https://my.skribble.com/login
      tryItOut:
        label: Try it out
        href: https://my.skribble.com/signup
    footer:
      navigation:
        titleColumn1: Platform
        titleColumn2: About Skribble
      newsletterTitle: Newsletter
      newsletterText: Electronic signatures and digital trust are hot topics. Stay up to date! See our <a href="/privacy">privacy policy</a>.