backend:
  name: git-gateway
media_folder: "static/images/uploads"
public_folder: "/"
collections:
  - name: home
    label: "Home"
    folder: "/"
    fields:
      - name: title
        widget: "string"
      - name: "body"
        widget: "markdown"