backend:
  name: git-gateway
media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/german/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields: 
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "markdown"
